services:
  keycloak:
    image: docker.io/keycloak/keycloak
    restart: always
    env_file:
      - ../../.env
    depends_on:
      - postgresql
  minio:
    image: docker.io/minio/minio
    restart: always
    env_file:
      - ../../.env
  postgresql:
    image: docker.io/postgres
    restart: always
    env_file:
      - ../../.env
  mongo:
    image: docker.io/mongo
    restart: always
    env_file:
      - ../../.env
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../..
      target: ${BACKEND_TARGET}
    tty: ${BACKEND_TTY}
    env_file:
      - ../../.env
    depends_on:
      - keycloak
      - minio
      - postgresql
      - mongo
    #models:
    #  - llama
    volumes:
      - backend_data:/data

volumes:
  postgresql_data:
  minio_data:
  mongo_data:
  keycloak_data:
  backend_data:

#models:
#  llama:
#    model: docker.io/ai/llama3.3:latest
